### ISSUE TITLE
Issue with hitslop

### ISSUE THREAD

**Issue by Hirbod** [gorhom/react-native-sticky-item#4]
Hello @gorhom . I wanted to thank you again, after a long time of trying I was able to replace Recylerview with your library and achieved a very satisfying performance. 

The only problem I could not solve yet is the hitslop of the sticky element. Since the element overlays my thumbs, which are also clickable, I often have two actions (once opening my story and once the action on the button).

How can I optimize this? I would like to be able to define a larger area so that no touch is registered on the thumbnail.

I have made you a video to illustrate this.
https://streamable.com/pmlrit

Unfortunately you can't see my finger on the video, but I always try to open the action of the sticky element only, but I always open the story too. Only if I touch in a very special area I get it right but the UX is not so good at this.

**Comment by gorhom** [comment]
this been fixed with [Release v1.2.0](https://github.com/gorhom/react-native-sticky-item/releases/tag/v1.2.0)

**Comment by Hirbod** [comment]
@gorhom unfortunately its not fixed on android. And android really doesn't care where in that area I tab, it always fires both the item and sticky press. iOS is working perfectly fine

**Comment by gorhom** [comment]
ughhh , okay i'll look into later today 👍

**Comment by gorhom** [comment]
hi @Hirbod could you try install from master, it should solve hitslop and double press event on android 👍

```
yarn add ssh://git@github.com:gorhom/react-native-sticky-item
```

**Comment by Hirbod** [comment]
Well, a big "dank u" mate. Works perfectly! Now iOS and Android have feature parity :)

**Comment by gorhom** [comment]
graag gedaan "du bist willkommen", now its [release v1.2.1](https://github.com/gorhom/react-native-sticky-item/releases/tag/v1.2.1) :)

**Comment by Hirbod** [comment]
PS: your implementation with reanimated is MUCH smoother then facebook's :D (at least on iOS)

**Comment by gorhom** [comment]
yeah i notice while i was analysing its animation 😅
